ghost_fnk/ghost/urls.py
from django.urls import path
from . import views
from .views import RegisterUser, index, FilterApplications
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('applications/', views.ApplicationListView, name='applications'),
    path('applications/<int:pk>', views.ApplicationDetailView.as_view(), name='application-detail'),
    path('application/create/', views.ApplicationCreate.as_view(), name='application-create'),
    path('application/<int:pk>/delete/', views.ApplicationDelete.as_view(), name='application-delete'),
    path('applications/filter/', FilterApplications.as_view(), name='applications-filter'),
    path('categories/', views.CategorysAdmin.as_view(), name='categories'),
    path('categories/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('categories/delete/<int:pk>', views.CategoryDelete.as_view(), name='category-delete'),
    path('application/<int:pk>/status-change-ATJ/', views.ATJChange.as_view(), name='status-change-ATJ'),
    path('application/<int:pk>/status-change-D/', views.DChange.as_view(), name='status-change-D'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

ghost_fnk/ghost_fnk/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('ghost/', include('ghost.urls')),
                  path('', RedirectView.as_view(url='/ghost/', permanent=True)),
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

ghost_fnk/ghost/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import validate_image_file_extension, FileExtensionValidator
from django.urls import reverse

class User(AbstractUser):
    username = models.CharField(max_length=150, verbose_name='Login', unique=True, blank=False)
    first_name = models.CharField(verbose_name="First name", max_length=150, blank=False)
    last_name = models.CharField(verbose_name="Last name", max_length=150, blank=False)
    email = models.EmailField(verbose_name="Email address", blank=False)
    patronymic = models.CharField(max_length=150, verbose_name='Patronymic', blank=False)
    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Category name', blank=False, unique=True)

    def __str__(self):
        return self.name


class Application(models.Model):
    name = models.CharField(max_length=150, verbose_name='Application name', blank=False)
    description = models.CharField(max_length=254, verbose_name='Application description', blank=False)
    category = models.ForeignKey("Category", max_length=150, verbose_name='Application category', blank=False,
                                 on_delete=models.CASCADE)
    NEW = 'N'
    ACCEPTED_THE_JOB = 'ATJ'
    DONE = 'D'

    AppStatus = [
        (NEW, 'New'),
        (ACCEPTED_THE_JOB, 'Accepted the job'),
        (DONE, 'Done')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")
    status = models.CharField(max_length=150, verbose_name='Appication status', choices=AppStatus,
                              default=NEW)
    time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='user/', default='media/default.jpeg',
    validators =[validate_image_file_extension,
                  FileExtensionValidator(['bmp', 'jpeg', 'jpg', 'png'],
                                         message='Allowed types: bmp, jpeg, jpg. png')])
    image_status = models.ImageField(upload_to='user/', verbose_name='Image for status',default='media/default.jpeg',
    validators =[validate_image_file_extension,
                  FileExtensionValidator(['bmp', 'jpeg', 'jpg', 'png'],
                                         message='Allowed types: bmp, jpeg, jpg. png')])
    comm = models.CharField(max_length=150, verbose_name='comment', blank=False)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('application-detail', args=[str(self.id)])

ghost_fnk/ghost/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible
from .models import User


@deconstructible
class FIOValidator(validators.RegexValidator):
    regex = r"^[а-яА-Я\s-]+$"
    message = "Please enter valid details. This value may contain only Cyrillic letters, spaces, and dashes."


@deconstructible
class LoginValidator(validators.RegexValidator):
    regex = r"^[a-zA-Z-]+$"
    message = "Enter a valid login. This value may contain only Latin letters and '-'."


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Login', max_length=150, widget=forms.TextInput(attrs={'class': 'form-input'})),
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'})),
    password1 = forms.CharField(label='Password'),
    password2 = forms.CharField(label='Password'),
    first_name = forms.CharField(label='Name', max_length=150, widget=forms.TextInput(attrs={'class': 'form-input'})),
    last_name = forms.CharField(label='Surname', max_length=150, widget=forms.TextInput(attrs={'class': 'form-input'})),
    patronymic = forms.CharField(label='Patronymic', max_length=150,
                                 widget=forms.TextInput(attrs={'class': 'form-input'})),
    agree_to_processing = forms.BooleanField(required=True,
                                             widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'patronymic', 'password1', 'password2',
                  'agree_to_processing']

    def clean_username(self):
        username = self.cleaned_data['username']
        validator = LoginValidator()
        try:
            validator(username)
        except ValidationError:
            raise forms.ValidationError(validator.message)

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('This username is already taken. Please choose another one.')

        return username

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        validator = FIOValidator()
        try:
            validator(first_name)
        except ValidationError:
            raise forms.ValidationError(validator.message)

        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        validator = FIOValidator()
        try:
            validator(last_name)
        except ValidationError:
            raise forms.ValidationError(validator.message)

        return last_name

    def clean_patronymic(self):
        patronymic = self.cleaned_data['patronymic']
        validator = FIOValidator()
        try:
            validator(patronymic)
        except ValidationError:
            raise forms.ValidationError(validator.message)

        return patronymic


class ApplicationChekerForAdmin(forms.ModelForm):
    def clean(self):
        status = self.cleaned_data.get('status')
        if self.instance.status != 'N':
            raise forms.ValidationError({'status': "The status can only be changed for new applications"})
        elif self.instance.status == 'D' and self.instance.image.count() < 1:
            raise forms.ValidationError({'status': "The status - Done need had min 1 image"})

ghost_fnk/ghost/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views import View, generic
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import RegisterUserForm
from .models import Application, Category
from django.core.exceptions import ValidationError


def index(request):
    counter_for_indx = Application.objects.filter(status__exact='D').order_by('time')[:4]
    counter_for_indx_job = Application.objects.filter(status__exact='ATJ').count()
    return render(
        request, 'index.html',
        context={'counter_for_indx': counter_for_indx, 'counter_for_indx_job': counter_for_indx_job}
    )

class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')


class ApplicationListView(generic.ListView):
    template_name = 'application_list.html'


@login_required()
def ApplicationListView(request):
    user = request.user
    template_name = 'application_list.html'
    if user:
        application_list = Application.objects.filter(user=request.user).order_by('time')
    else:
        application_list = Application.objects.all().order_by('time')

    context = {
        'application_list': application_list
    }
    return render(request, template_name, context)


class ApplicationDetailView(generic.DetailView):
    model = Application
    context_object_name = 'application'
    template_name = 'application_detail.html'


class ApplicationCreate(CreateView):
    model = Application
    fields = ['name', 'description', 'category', 'image']

    template_name = 'application_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ApplicationCreate, self).form_valid(form)

    def clean_image(self):
        image = self.cleaned_data.get("image")
        image_size = image.size
        str_file = str(image)
        if str_file.endswith('.jpg') and image_size <= 2097152:
            return image
        elif str_file.endswith('.jpeg') and image_size <= 2097152:
            return image
        elif str_file.endswith('.png') and image_size <= 2097152:
            return image
        elif str_file.endswith('.bpm') and image_size <= 2097152:
            return image
        else:
            raise ValidationError(
                "Error: "
                "The file must have the following formats: jpg, jpeg, png, bmp and no more than 2MB in size."
            )


class ApplicationDelete(PermissionRequiredMixin, DeleteView):
    model = Application
    success_url = '/ghost/applications'
    permission_required = 'delete_application'
    template_name = 'application_form.html'

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception:
            return HttpResponseRedirect(
                reverse("application-delete", kwargs={"pk": self.object.pk})
            )


class FilterApplications(TemplateView, LoginRequiredMixin):
    template_name = 'application_list.html'

    def get(self, request):
        application_status = request.GET.get('status')

        if application_status:
            application_list = Application.objects.filter(status=application_status, user=request.user).order_by('time')
        else:
            application_list = Application.objects.all().order_by('time')

        context = {
            'application_list': application_list
        }
        return render(request, self.template_name, context)


class CategorysAdmin(generic.ListView):
    template_name = 'categories_list_admin.html'
    model = Category


class CategoryCreate(CreateView):
    model = Category
    fields = ['name']
    template_name = 'category_form.html'
    success_url = '/ghost/categories'

class CategoryDelete(DeleteView):
    model = Category
    permission_required = 'delete_category'
    template_name = 'category_conf_delete.html'
    success_url = '/ghost/categories'
    def catg_del(self):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception:
            return HttpResponseRedirect(
                reverse("category-delete", kwargs={"pk": self.object.pk})
            )
class ATJChange(UpdateView):
    model = Application
    fields = ['comm']
    template_name = 'change_conf.html'
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.status ='ATJ'
        instance.save()
        return redirect('applications')

class DChange(UpdateView):
    model = Application
    fields = ['image_status']
    template_name = 'change_conf.html'
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.status ='D'
        instance.save()
        return redirect('applications')

ghost_fnk/ghost/templates/application_confirm_delete.html
{% extends "home_str.html" %}

{% block content %}

<h1>Delete application: {{ application }}</h1>

{% if application.application_list.all %}

<p>You can't delete this application until all their applications have been deleted:</p>
<ul>
  {% for application in application.applications.all %}
    <li><a href="{% url 'application-detail' application.pk %}">{{application}}</a> ({{application.applications.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the application?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

ghost_fnk/ghost/templates/application_detail.html
{% extends "home_str.html" %}

{% block content %}
<h1>Application: {{ application.name }}</h1>

<p><strong>Name:</strong>{{ application.name }}</p>
<p><strong>Description:</strong> {{ application.description }}</p>
<p><strong>Category:</strong> {{ application.category }}</p>
<p><strong>Status:</strong> {{ application.status }}</p>
<p><strong>Time:</strong> {{ application.time }}</p>
<p><strong>Image:</strong></p>
<img style="max-width:100px; max-height:100px;" class="img" src="{{ application.image.url }}">
{% if application.status == 'ATJ' %}
<p>Application at the job</p>
<p><strong>Comment:</strong> {{ application.comm }}</p>
{% endif %}
{% if application.status == 'D' %}
<p>Application done</p>
<p><strong>Image on done:</strong></p>
<img style="max-width:100px; max-height:100px;" class="img"
     src="{{ application.image_status.url }}">
{% endif %}
{% endblock %}

ghost_fnk/ghost/templates/application_form.html
{% extends "home_str.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

ghost_fnk/ghost/templates/application_list.html
{% extends "home_str.html" %}

{% block content %}
<h1>Applications</h1>
<p><a href="{% url 'application-create' %}">Create application</a></p>

{% if application_list %}
<ul>
    <form action="{% url 'applications-filter' %}" method="get" name="filter">
        <h4>Select filter</h4>
        <div>
            <select name="status">
                <option value="N">New</option>
                <option value="ATJ">At the job</option>
                <option value="D">Done</option>
            </select>
        </div>
        <button type="submit">Select</button>
    </form>
    {% for application in application_list %}
    <li>
        <p><strong>Time add:</strong> {{application.time}}</p>
        <p><strong>Name:</strong> {{application.name}}</p>
        <p><strong>Decsription:</strong> {{application.description}}</p>
        <p><strong>Category:</strong> {{application.category}}</p>
        <p><strong>Status:</strong> {{application.status}}</p>
        {% if application.status == 'ATJ' %}
        <p><strong>Comment:</strong> {{application.comm}}</p>
        {% endif %}
        {% if application.status == 'D' %}
        <p><strong>Image on done:</strong></p>
        <img style="max-width:100px; max-height:100px;" class="img"
             src="{{ application.image_status.url }}">
        {% endif %}
        {% if user.is_staff %}
        {% if application.status == 'N' %}
        <p><a href="{% url 'application-delete' application.id %}">Delete application</a> | <a
                href="{% url 'status-change-ATJ' application.pk %}">Status --> ATJ</a> | <a
                href="{% url 'status-change-D' application.pk %}">Status --> D</a></p>
        {% else %}
        <p>You cannot delete this application because it has already been made or is in progress.</p>
        {% endif %}
        {% endif %}
        <p><strong>-------------------------------------------------------------</strong></p>
    </li>
    {% endfor %}
</ul>
{% else %}
<ul>
    <form action="{% url 'applications-filter' %}" method="get" name="filter">
        <h4>Select filter</h4>
        <div>
            <select name="status">
                <option value="N">New</option>
                <option value="ATJ">At the job</option>
                <option value="D">Done</option>
            </select>
        </div>
        <button type="submit">Select</button>
    </form>
    <p>There are no applications</p>
</ul>
{% endif %}
{% endblock %}

ghost_fnk/ghost/templates/application_list_admin.html
{% extends "home_str.html" %}

{% block content %}
<h1>Categories</h1>
<p><a href="{% url 'category-create' %}">Create category</a></p>


{% for category in application_categories %}
<ul>
    <li>{{ category }}</li>
</ul>

{% endfor %}

{% endblock %}

ghost_fnk/ghost/templates/categories_list_admin.html
{% extends "home_str.html" %}

{% block content %}
<h1>Categories</h1>
<p><a href="{% url 'category-create' %}">Create category</a></p>


{% for category in category_list %}
<ul>
    <li>{{ category }} <a href="{% url 'category-delete' pk=category.id %}"> --del--</a></li>
</ul>

{% endfor %}

{% endblock %}

ghost_fnk/ghost/templates/category_conf_delete.html
{% extends "home_str.html" %}
{%block content%}
<p>Confirm deleting the category</p>

<form method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

ghost_fnk/ghost/templates/category_form.html
{% extends "home_str.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

ghost_fnk/ghost/templates/change_conf.html
{% extends "home_str.html" %}
{%block content%}
<p>Confirm change status</p>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_table}}
  <input type="submit" value="Change">
</form>

{% endblock %}

ghost_fnk/ghost/templates/home_str.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Ghost_functionality</title>{% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
{% block sidebar %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            <ul class="sidebar-nav">
                <ol><a href="{% url 'index' %}">Home</a></ol>
                {% if user.is_authenticated %}
                <ul class="sidebar-nav">
                    <li>User: {{ user.get_username }}</li>
                </ul>
                <ol><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></ol>
                <ol><a href="{% url 'applications' %}?next={{ request.path }}">Applications</a></ol>

                {% else %}
                <ol><a href="{% url 'login' %}?next={{ request.path }}">Login</a> | <a
                        href="{% url 'register' %}?next={{ request.path }}">SignUp</a></ol>

                {% endif %}
                {% if user.is_staff %}
                <hr>
                <ul>
                    <li>Staff</li>
                    <ol><a href="{% url 'categories' %}">Categories</a></ol>
                </ul>
                {% endif %}
            </ul>
            </ul>

        </div>
        {% endblock %}

    </div>
    <div class="col-sm-10 ">{% block content %}{% endblock %}
        {% block pagination %}{% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}</span>
        </div>
        {% endif %}
        {% endblock %}
    </div>
</div>
</div>
</body>
</html>

ghost_fnk/ghost/templates/index.html
{% extends "home_str.html" %}
{% block title %}<title>Ghost_functionality</title>{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<h3>Welcome to Design.Pro </h3>
{% if counter_for_indx %}
<p><strong>Applications in progress:</strong> {{ counter_for_indx_job }}</p>
<p><strong>Completed applications</strong></p>
<p><strong>-------------------------------------------------------------</strong></p>
{% for i in counter_for_indx %}
<p><strong>Time add:</strong> {{i.time}}</p>
<p><strong>Name:</strong> {{i.name}}</p>
<p><strong>Category:</strong> {{i.category}}</p>
<p><strong>Image on start:</strong></p>
<img style="max-width:100px; max-height:100px;" class="img" src="{{ i.image.url }}">
<p><strong>Image on done:</strong></p>
<img style="max-width:100px; max-height:100px;" class="img" src="{{ i.image_status.url }}">

<p><strong>-------------------------------------------------------------</strong></p>
{% endfor %}
{% else %}
<p>We don't have completed applications</p>
{% endif %}
{% endif %}
{% endblock %}

ghost_fnk/ghost/templates/register.html
{% extends 'home_str.html' %}
<style>
    .da {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

</style>
{% block content %}

<h2>Signup</h2>
<div class="da">
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit">Signup</button>
    </form>
</div>
{% endblock %}